---
title: "Logistic Regression"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
```

The notes for the topics on this page can be found in the lectures 13, 14, and 15 folders on Canvas. 

# {.tabset .tabset-fade}

## R

### Group level data

```{r}
library(broom)

trial <- tibble(
  estrogen = c(rep(c("no", "yes"), 2)), 
  event = c(0, 0, 1, 1), 
  count = c(7479, 7755, 623, 751)
)

trial_mod <- glm(event ~ estrogen, weights = count, data = trial, 
                 family = "binomial")

summary(trial_mod)

broom::tidy(trial_mod) %>% 
  filter(term != "(Intercept)") %>% 
  mutate(odds_ratio = exp(estimate), 
         lower = exp(estimate - 1.96*std.error), 
         upper = exp(estimate + 1.96*std.error))
```

### Individual level data

```{r}
library(broom)

low_bwt <- read_csv("../../data/lowbwt.csv")

bwt_mod <- glm(low ~ age, data = low_bwt, family = "binomial")

summary(bwt_mod)

broom::tidy(bwt_mod) %>% 
  filter(term != "(Intercept)") %>% 
  mutate(odds_ratio = exp(estimate), 
         lower = exp(estimate - 1.96*std.error), 
         upper = exp(estimate + 1.96*std.error))

broom::tidy(bwt_mod) %>% 
  filter(term != "(Intercept)") %>% 
  transmute(or_5 = exp(estimate * 5), 
            lower = exp(estimate * 5 - 1.96*std.error*5), 
            upper = exp(estimate * 5 + 1.96*std.error*5))
```

## SAS

### Group level data

A single binary predictor: 

```{r, engine = "sas", engine.path = "C:/Program Files/SASHome/SASFoundation/9.4/sas.exe"}
title 'Example Estrogen Trial'; 
data trial; 
  input estrogen events trials; 
  cards; 
  0 623 8102
  1 751 8506
  ; 
run; 
  
proc format; 
  value estfmt 0 = 'placebo' 
               1 = 'estrogen'; 
run; 
               
proc logistic data = trial; 
  class estrogen (ref = 'placebo') / param = ref; 
  model events/trials = estrogen / cl; 
  format estrogen estfmt.; 
run; 
```

A multivariable example: 

```{r, engine = "sas", engine.path = "C:/Program Files/SASHome/SASFoundation/9.4/sas.exe"}
title'ExampleInfection and Treatment adjusting for Hospital Risk';
data hosp;
  input hospital $ treatment $ events trials;
  cards;
  low treat 5 104
  low cont 10 105
  med treat 35 110
  med cont 102 197
  high treat 95 105
  high cont 99 104
  ;
run;
  
proc logistic data = hosp; 
  class hospital (ref = 'low')
        treatment (ref = 'cont') / param = ref; 
  model events/trials = treatment hospital / cl; 
run; 
```

### Individual level data

```{r, engine = "sas", engine.path = "C:/Program Files/SASHome/SASFoundation/9.4/sas.exe"}
title 'Example Low Birth-weight and Maternal Age'; 
proc import datafile = 'C:\Users\niwi8\OneDrive\Documents\p8120_ta\data\lowbwt.csv'
            out = lowbwt
            dbms = csv; 
run; 
            
proc logistic data = lowbwt descending; 
  model low = age / waldrl; 
  units age = 5; 
run; 
```






