---
title: "SAS"
output:
  html_document: 
    toc: true
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Getting started

This document is intended to be used as a guide to SAS for P8120 (Analysis of Categorical Data). This document is not exhaustive; please consult one of the TA's, Dr. Mauro, or the online SAS user [guide](https://support.sas.com/documentation/cdl/en/statug/63962/HTML/default/viewer.htm#titlepage.htm) for more help if needed. SAS is available on all computers at CUMC or can be purchased through the IT department with a student discount (Windows computers only).

SAS is a powerful statistical software and programming language commonly used in universities, government, and the private sector. Programming in SAS can roughly be broken down into two sections: data steps (begun by a `data` statement) and statistical procedures (begun by a `proc` statement). Almost all code blocks in SAS begin with one of these two statements and almost all code blocks are ended with `run;`. Within code blocks, arguments in SAS are ended with a semicolon. 

### Importing data and manipulation

Importing data in SAS can be done a couple of different ways. We recommend using one of two methods: the import procedure or a data step. 

The import procedure is the most straightforward way of importing data into SAS. The procedure requires two arguments and a third optional requirement is recommended: `out`, `datafile`, and `dbms`. The `out` argument specifies the name of the newly created SAS dataset; the `datafile` argument specifies the complete path for the file containing the data to be imported in quotation marks; the `dbms` argument is optional and specifies the file type to be parsed. The most commonly used identifiers are `csv`, `tab`, `xlsx`, and `dlm`. If importing a csv file, this argument is not necessary. Further help can be found [here](http://support.sas.com/documentation/cdl/en/proc/65145/HTML/default/viewer.htm#n18jyszn33umngn14czw2qfw7thc.htm). The syntax is as follows: 

```{}
proc import out = <SAS dataset name>
            datafile = "filepath"
            dbms = <identifier> replace;
run; 
```

The data step in SAS is where all data manipulation occurs, this includes being able to import data. While using a data step to import data is more complicated, it offers the user more control over the import process. The first argument to any data step is the name of the dataset you are creating. When importing a datafile, the next argument is `infile` followed by the full path to the data on your computer, the `delimiter` argument which specifies the delimiter used to separate values (',' for a csv), the `missover` argument, the `firstobs` argument (if a file already has variable names in it set this to 2, otherwise set to 1), and `DSD`. Following the infile argument is the `input` argument where you can specify variable names and whether or not they should be treated as numeric or categorical variables; if a variable should be treated as categorical, it's name is followed by a $. The syntax is as follows: 

```{}
data <insert SAS dataset name>
  infile 'file path'
    delimiter = ','
    missover
    firstobs = 2
    DSD; 
  input <name of a numeric variable> <name of a categorical variable> $; 
run; 
```

### Output delivery system (ODS)

You will be asked to include SAS output in homework assignments. SAS has a built in output delivery system (ODS) that can save output as an rtf file to be used in a word document. The basic usage is: 

```{}
ods rtf file = "filepath and name";
<procedure code>
ods rtf close; 
```

You are not required to use this method when including SAS output in assignments.

### Hypothesis tests

Use the following table to locate procedures for hypothesis tests. If you are unsure of the usage of a procedure, refer to the online SAS guide. Lecture numbers are linked to examples. 

|Hypothesis test                                  | SAS procedure      | Arguments needed                    | Lecture number                   |
|-------------------------------------------------|--------------------|-------------------------------------|:--------------------------------:|
|Confidence intervals, proportions                |`proc freq`         |Same as normal and exact             | [3](ci_single_proportion.html)   |
|One sample test proportions, normal approximation|`proc freq`         |`binomial(p = <insert null>)`        | [4](hypothesis_single_prop.html) |
|One sample test proportions, exact               |`proc freq`         |`exact binomial`                     | [4](hypothesis_single_prop.html) |
|Chi-squared                                      |`proc freq`         |`chisq expected`                     | [8](chi_squared_fisher.html)     |
|Fisher's exact                                   |`proc freq`         |Same as chi-squared                  | [8](chi_squared_fisher.html)     |
|Likelihood ratio test                            |`proc freq`         |Same as chi-squared                  | [9](lrt_2_sample.html)           |
|Two sample test of proportions                   |`proc freq`         |`expected riskdiff(equal var = null)`| [9](lrt_2_sample.html)           |
|McNemar's test                                   |                    |                                     |                                  |
|Logistic regression                              |`proc logistic`     |                                     |                                  |
|GOF & Hosmer Lemeshow                            |                    |                                     |                                  |
|Conditional logistic regression                  |                    |                                     |                                  |
|Cochran Armitage Trend test                      |                    |                                     |                                  |
|Brewlow Day test                                 |                    |                                     |                                  |
              
### Measures of association

Use the following table to locate procedures for measures of association. If you are unsure of the usage of a procedure, refer to the online SAS guide. Lecture numbers are linked to examples. 

| Measure                                         | SAS procedure      | Arguments needed                    | Lecture number                   |
|-------------------------------------------------|--------------------|-------------------------------------|:--------------------------------:|
|Odds ratio (2 x k table)                         | `proc freq`        |`relrisk`                            |[5 & 7](measures_association.html)|
|Risk ratio (2 x k table)                         | `proc freq`        |`relrisk`                            |[5 & 7](measures_association.html)|
|Risk difference                                  | `proc freq`        |`riskdiff`                           |[5 & 7](measures_association.html)|

### Power

Use the following table to locate procedures for power. If you are unsure of the usage of a procedure, refer to the online SAS guide. Lecture numbers are linked to examples. 

| Power analysis                     | SAS procedure       | Notes                      | Lecture          |
|------------------------------------|---------------------|----------------------------|:----------------:|
| Power from sample size             | `proc power`        | `power = .`                | [10](power.html) |
| Sample size from power (balanced)  | `proc power`        | `power = .`                | [10](power.html) |
| Sample size from power (unbalanced)| `proc power`        | must specify `groupweights`| [10](power.html) |
